import { useRef, useState } from "react";
import "./App.css";

// ***** 你目前的 5 題資料 *****
const QUESTIONS = [
  {
    id: 1,
    type: "image",
    src: "/q1-image.png",
    correctDirection: "right",
    explanation: "This was generated by ChatGPT."
  },
  {
    id: 2,
    type: "video",
    src: "/q2-video.MOV",
    correctDirection: "left",
    explanation: "This video was taken by the developer."
  },
  {
    id: 3,
    type: "image",
    src: "/q3-image.JPG",
    correctDirection: "left",
    explanation: "This photo of Second Joffre Lake was taken by the developer. It took a long time to get up there."
  },
  {
    id: 4,
    type: "audio",
    src: "/q4-audio.mp3",
    correctDirection: "right",
    explanation: "This was generated by ElevenLabs."
  },
  {
    id: 5,
    type: "video",
    src: "/q5-video.mp4",
    correctDirection: "right",
    explanation: "This video was generated by invideo."
  }
];

function App() {
  const [currentIndex, setCurrentIndex] = useState(0);
  const [showResult, setShowResult] = useState(false);
  const [lastResult, setLastResult] = useState(null);
  const [dragX, setDragX] = useState(0);
  const [isDragging, setIsDragging] = useState(false);
  const startXRef = useRef(0);
  const cardRef = useRef(null);

  const hasMoreCards = currentIndex < QUESTIONS.length;
  const currentQuestion = QUESTIONS[currentIndex];

  // 判定答對/錯
  const handleAnswer = (direction, question) => {
    const isCorrect = direction === question.correctDirection;

    setLastResult({
      isCorrect,
      explanation: question.explanation
    });

    setShowResult(true);
    setDragX(0);
    setIsDragging(false);
  };

  // ----- 拖曳邏輯 -----
  const handlePointerDown = (e) => {
    if (!hasMoreCards || showResult) return;
    setIsDragging(true);
    startXRef.current = e.clientX;
    cardRef.current?.setPointerCapture(e.pointerId);
  };

  const handlePointerMove = (e) => {
    if (!isDragging) return;
    const deltaX = e.clientX - startXRef.current;
    setDragX(deltaX);
  };

  const handlePointerUp = (e) => {
    if (!isDragging) return;

    cardRef.current?.releasePointerCapture(e.pointerId);

    const threshold = 80;

    if (dragX > threshold) {
      handleAnswer("right", currentQuestion);
    } else if (dragX < -threshold) {
      handleAnswer("left", currentQuestion);
    } else {
      setDragX(0);
    }

    setIsDragging(false);
  };

  const handleClosePopup = () => {
    setShowResult(false);
    setCurrentIndex((prev) => prev + 1);
  };

  // 卡片拖曳動畫
  const cardStyle = {
    transform: `translateX(${dragX}px) rotate(${dragX / 25}deg)`,
    transition: isDragging ? "none" : "transform 0.2s ease-out"
  };

  // 根據題目類型載入媒體
  const renderMedia = (q) => {
    if (q.type === "image")
      return <img src={q.src} alt="" className="card-media" />;

    if (q.type === "video")
      return <video src={q.src} className="card-media" controls />;

    if (q.type === "audio")
      return (
        <audio src={q.src} controls className="audio-player" />
      );

    return null;
  };

  return (
    <div className="app-root">
      <div className="game-container">
        <h1 className="title">Swipe Right for AI</h1>

        <div className="card-area">
          {hasMoreCards ? (
            <div
              ref={cardRef}
              className="card"
              style={cardStyle}
              onPointerDown={handlePointerDown}
              onPointerMove={handlePointerMove}
              onPointerUp={handlePointerUp}
              onPointerCancel={handlePointerUp}
            >
              <p className="card-count">
                {currentIndex + 1} / {QUESTIONS.length}
              </p>
              <div className="card-content">{renderMedia(currentQuestion)}</div>
            </div>
          ) : (
            <div className="finished">
              <p>You&apos;ve completed all questions 🎉</p>
            </div>
          )}
        </div>

        {hasMoreCards && (
          <p className="subtitle">
            Swipe <strong>right</strong> if your detector flags AI. <br />
            Swipe <strong>left</strong> if it's just regular tech. <br />
            If dragging the picture doesn’t work, try dragging the white card instead.
          </p>
        )}
      </div>

      {/* Popup */}
      {showResult && lastResult && (
        <div className="overlay">
          <div className="popup">
            <div className="icon">{lastResult.isCorrect ? "✅" : "❌"}</div>

            <p className="popup-title">
              {lastResult.isCorrect ? "Correct!" : "Not quite"}
            </p>

            {/* 答錯才顯示 explanation */}
            {!lastResult.isCorrect && (
              <p className="popup-text">{lastResult.explanation}</p>
            )}

            <button className="popup-button" onClick={handleClosePopup}>
              Continue
            </button>
          </div>
        </div>
      )}
    </div>
  );
}

export default App;
